# Generated by Django 5.0.7 on 2024-09-13 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_shift_shift_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=10, null=True, unique=True, verbose_name='username'),
        ),
    ]
