# Generated by Django 5.0.7 on 2024-10-14 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_post_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='shift_type',
            field=models.CharField(choices=[('△', '△'), ('◯', '◯'), ('11~', '11~'), ('17~', '17~'), ('☆', '☆'), ('◎', '◎'), ('✕', '✕')], max_length=10),
        ),
    ]
